AWSTemplateFormatVersion: 2010-09-09
Description: >
  Tenable.io AWS connector enablement.
  Creates a trust relationship between your AWS accounts and Tenable's AWS account with permissions to get EC2 instance
  data.
Metadata:
  Version: 1.1.0
  AWS::CloudFormation::Interface:
    ParameterGroups:
      - Label:
          default: General Properties
        Parameters:
          - pGLCTSolutionVersion
      - Label:
          default: Trust relationship Configuration
        Parameters:
          - pPrincipalAws
          - pRoleName
          - pTenableExternalId
      - Label:
          default: Tagging Configuration
        Parameters:
          - pTagEnvironment
          - pTagSDLC
          - pTagApplicationName
          - pTagApplicationRole
          - pTagCluster
          - pTagDataClassification
          - pTagCompliance
          - pTagDataRetention
          - pTagMapMigrated
          - pTagProjectName
          - pTagProductOwner
          - pTagTechnicalOwner
          - pTagCostCenter
          - pTagBusinessUnit
          - pTagBusinessImpact
          - pTagEscalationPath
          - pTagKnowledgeBase
          - pTagHoursOfOperation
          - pTagMaintenanceWindow
          - pTagBackupSchedule
          - pTagOptOut
          - pTagDeploymentMethod
Parameters:
  pGLCTSolutionVersion:
    Description: The Global Logic solution version. Used to trigger updates on the nested StackSets.
    Type: String
  pPrincipalAws:
    Type: String
    Default: arn:aws:iam::012615275169:role/keyless_connector_role
    Description: The Amazon Resource Name (ARN) of the Tenable.io AWS account to establish a trust relationship with.
    ConstraintDescription: The Amazon Resource Name (ARN) of the Tenable.io AWS account must be set to "arn:aws:iam::012615275169:role/keyless_connector"
    AllowedPattern: 'arn:aws:iam::[0-9]+:role+/.*'
  pRoleName:
    Type: String
    Default: tenableio-connector
    Description: The name of the IAM trusted role.
    ConstraintDescription: The IAM trusted role must be set to "tenableio-connector"
    AllowedValues:
      - tenableio-connector
      - tenableio-connector_dev
  pTenableExternalId:
    Type: String
    Default: 6e2981a5-dbb6-47cf-bebd-9037ad9c0e5c
    Description: The external ID from the connector configuration screen.
    ConstraintDescription: The external ID must match a Tenable.io container UUID format ^[0-9a-z]+-[0-9a-z]+-[0-9a-z]+-[0-9a-z]+-[0-9a-z]+$
    AllowedPattern: '^[0-9a-z]+-[0-9a-z]+-[0-9a-z]+-[0-9a-z]+-[0-9a-z]+$'
  pTagEnvironment:
    Type: String
    Description: Select the Name of the Environment
    AllowedValues:
      - Production
      - Non-Production
  pTagSDLC:
    Type: String
    Description: Distinguish between SDLC Environments e.g., Dev, Test, SIT, UAT
    AllowedValues:
      - Dev
      - Test
      - SIT
      - UAT
      - Pre-Prod
      - Prod
  pTagApplicationName:
    Type: String
    Description: Identify resources that are related to a specific application
  pTagApplicationRole:
    Type: String
    Description: Identify the function of a particular resource e.g., Web Server, Message Broker, Database Server
  pTagCluster:
    Type: String
    Description: Identify resource farms that share a common configuration and perform a specific function for an application
  pTagDataClassification:
    Type: String
    Description: Identify the specific data confidentiality level a resource supports
    AllowedValues:
      - Public
      - Private
      - Confidential
      - Restricted
    Default: Private
  pTagCompliance:
    Type: String
    Description: Identify the specific compliance requirements that resources must adhere to e.g., PCI-DSS, HIPAA, ISO27001
  pTagDataRetention:
    Type: String
    Description: Identify the data retention policy applied to the resources (S3, ECR, CloudWatch Logs, EC2 AMI, EBS Snapshots, RDS Snapshot)
    AllowedValues:
      - 1
      - 3
      - 5
      - 7
      - 14
      - 30
      - 60
      - 90
      - 120
      - 150
      - 180
      - 365
      - 400
      - 545
      - 731
      - 1827
      - 3653
  pTagMapMigrated:
    Type: String
    Description: Identify resources that have been migrated as part of the AWS Migration Acceleration Program (MAP) for funding purposes
  pTagProjectName:
    Type: String
    Description: Identify projects that the resource supports
  pTagProductOwner:
    Type: String
    Description: Identify who is commercially responsible for the resource
  pTagTechnicalOwner:
    Type: String
    Description: Identify who is technically responsible for the resource
  pTagCostCenter:
    Type: String
    Description: Identify the cost center associated with a resource, typically for cost allocation and tracking
  pTagBusinessUnit:
    Type: String
    Description: Identify the business unit associated with a resource, typically for cost allocation and tracking
  pTagBusinessImpact:
    Type: String
    Description: Identify the business impact associated with the resource
    AllowedValues:
      - Critical
      - High
      - Medium
      - Low
    Default: Medium
  pTagEscalationPath:
    Type: String
    Description: Identify the next point of contact for a resource in an incident e.g, DevOps Team, 3rd Party Company
  pTagKnowledgeBase:
    Type: String
    Description: Identifies the location for knowledge base articles/wikis for the resource
  pTagHoursOfOperation:
    Type: String
    Description: Identify the hours of operation for a resource e.g., 24*7, 06:00 - 22:00 Monday - Friday, 08:00 - 18:00 Monday - Friday
    AllowedValues:
      - 24x7
      - 16x5
      - 9x5
    Default: 24x7
  pTagMaintenanceWindow:
    Type: String
    Description: Identify the hours in which a resource is available for maintenance to occur
  pTagBackupSchedule:
    Type: String
    Description: Identify the backup schedule for a resource
  pTagOptOut:
    Type: String
    Description: Identify whether a resource should be excluded from maintenance activities e.g., True, False
    AllowedValues:
      - "True"
      - "False"
    Default: "False"
  pTagDeploymentMethod:
    Type: String
    Description: Identify the method by which resources are deployed
    AllowedValues:
      - CloudFormation
      - Terraform
      - Manual
    Default: CloudFormation
Resources:
  rTenableConnectorRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Ref pRoleName
      Description: CloudFormation defined role for Tenable.io AWS connector enablement.
      Path: /
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          -
            Effect: Allow
            Principal:
              AWS: !Ref pPrincipalAws
            Action: "sts:AssumeRole"
            Condition:
              StringEquals:
                sts:ExternalId: !Ref pTenableExternalId
      Tags:
        - Key: Name
          Value: tenableio-connector
        - Key: Environment
          Value: !Ref pTagEnvironment
        - Key: SDLC
          Value: !Ref pTagSDLC
        - Key: ApplicationName
          Value: !Ref pTagApplicationName
        - Key: ApplicationRole
          Value: !Ref pTagApplicationRole
        - Key: Cluster
          Value: !Ref pTagCluster
        - Key: DataClassification
          Value: !Ref pTagDataClassification
        - Key: Compliance
          Value: !Ref pTagCompliance
        - Key: DataRetention
          Value: !Ref pTagDataRetention
        - Key: map-migrated
          Value: !Ref pTagMapMigrated
        - Key: ProjectName
          Value: !Ref pTagProjectName
        - Key: ProductOwner
          Value: !Ref pTagProductOwner
        - Key: TechnicalOwner
          Value: !Ref pTagTechnicalOwner
        - Key: BusinessUnit
          Value: !Ref pTagBusinessUnit
        - Key: CostCenter
          Value: !Ref pTagCostCenter
        - Key: BusinessImpact
          Value: !Ref pTagBusinessImpact
        - Key: EscalationPath
          Value: !Ref pTagEscalationPath
        - Key: KnowledgeBase
          Value: !Ref pTagKnowledgeBase
        - Key: HoursOfOperation
          Value: !Ref pTagHoursOfOperation
        - Key: MaintenanceWindow
          Value: !Ref pTagMaintenanceWindow
        - Key: BackupSchedule
          Value: !Ref pTagBackupSchedule
        - Key: OptOut
          Value: !Ref pTagOptOut
        - Key: DeploymentMethod
          Value: !Ref pTagDeploymentMethod
  rTenableConnectorPolicy:
    Type: AWS::IAM::Policy
    Properties:
      PolicyName: tenableio-connector-policy
      PolicyDocument:
        Version: 2012-10-17
        Statement:
          - Action:
              - "ec2:DescribeInstances"
              - "cloudtrail:LookupEvents"
              - "cloudtrail:ListTags"
              - "cloudtrail:GetTrailStatus"
              - "cloudtrail:GetEventSelectors"
              - "cloudtrail:DescribeTrails"
              - "organizations:ListAccounts"
            Effect: "Allow"
            Resource: "*"
            Sid: "TioConnector"
          - Action:
              - "iam:GetRolePolicy"
            Effect: "Allow"
            Resource: "arn:aws:iam::*:role/tenableio-connector"
            Sid: "TioRoleUpdate"
      Roles:
        - !Ref rTenableConnectorRole