AWSTemplateFormatVersion: 2010-09-09
Metadata:
  AWS::CloudFormation::Interface:
    ParameterGroups:
      - Label:
          default: General Properties
        Parameters:
          - pGLCTSolutionVersion
      - Label:
          default: Amazon CloudWatch Observability Access Manager setup
        Parameters:
          - pMonitoringAccountId
          - pManagementAccountId
          - pRootOrganizationalUnitId
          - pOrganizationId
Parameters:
  pMonitoringAccountId:
    Type: String
    Description: Monitoring Account ID, Used for the Org Observability
    AllowedPattern: "^[0-9]{12}$"
    ConstraintDescription: "This must be a 12 character string."
    MinLength: 12
    MaxLength: 12
  pManagementAccountId:
    Type: String
    Description: Management Account ID
    ConstraintDescription: "This must be a 12 character string."
    Default: ""
  pRootOrganizationalUnitId:
    Type: String
    Description: Organizational Unit ID, Used for the scope in the Org View
    AllowedPattern: ^(ou-[a-z0-9]{4,32}-[a-z0-9]{8,32}|r-[a-z0-9]{4,32})(,(ou-[a-z0-9]{4,32}-[a-z0-9]{8,32}|r-[a-z0-9]{4,32}))*$
    ConstraintDescription:
      Must be alphanumeric or special characters [., _, -]. In addition, the slash character ( / ) used to delineate hierarchies in parameter names.
  pOrganizationId:
    Type: String
    Description: Organizational Unit Id
    Default: ""
  pGLCTSolutionVersion:
    Description: The Global Logic solution version. Used to trigger updates on the nested StackSets.
    Type: String

Resources:
  rSink:
    Type: AWS::Oam::Sink
    Properties:
      Name: "OrgSink"
      Policy:
        Version: '2012-10-17'
        Statement:
        - Effect: Allow
          Principal: "*"
          Resource: "*"
          Action:
          - "oam:CreateLink"
          - "oam:UpdateLink"
          Condition:
            StringEquals:
              aws:PrincipalOrgID: !Ref pOrganizationId
            ForAllValues:StringEquals:
              oam:ResourceTypes:
                - "AWS::CloudWatch::Metric"
                - "AWS::Logs::LogGroup"
                - "AWS::XRay::Trace"
                - "AWS::ApplicationInsights::Application"
                - "AWS::InternetMonitor::Monitor"
  rSinkArnSSMParameter:
    Type: AWS::SSM::Parameter
    Properties:
      Name: /org/CloudWatchOAMSinkArn
      Type: String
      Tier: Advanced
      Value: !Ref rSink
      Description:  Amazon CloudWatch Observability Access Manager Organization Sink Arn
  rSinkArnSSMParameterRAMShare:
    Type: AWS::RAM::ResourceShare
    Properties:
      Name: SinkArnSSMParameterRAMShare
      AllowExternalPrincipals: false
      Principals:
        - !Sub arn:aws:organizations::${pManagementAccountId}:organization/${pOrganizationId}
      ResourceArns:
        - !Sub arn:aws:ssm:${AWS::Region}:${AWS::AccountId}:parameter/org/CloudWatchOAMSinkArn
