AWSTemplateFormatVersion: 2010-09-09
Description: "CloudFormation Module to Deploy S3 Buckets and Pre-Requisites required for VPC FlowLogs and Quicksight Dashboards"
Metadata:
  AWS::CloudFormation::Interface:
    ParameterGroups:
      - Label:
          default: Account Configuration
        Parameters:
          - pLogArchiveAccountId
          - pSharedServicesAccountId
      - Label:
          default: Data Retention Configuration
        Parameters:
          - pS3LifeCycleTransition
      - Label:
          default: Athena/Glue Configuration
        Parameters:
          - pAthenaQueryResultBucketArn
      - Label:
          default: Tagging Configuration
        Parameters:
          - pTagEnvironment
          - pTagSDLC
          - pTagApplicationName
          - pTagApplicationRole
          - pTagCluster
          - pTagDataClassification
          - pTagCompliance
          - pTagDataRetention
          - pTagMapMigrated
          - pTagProjectName
          - pTagProductOwner
          - pTagTechnicalOwner
          - pTagCostCenter
          - pTagBusinessUnit
          - pTagBusinessImpact
          - pTagEscalationPath
          - pTagKnowledgeBase
          - pTagHoursOfOperation
          - pTagMaintenanceWindow
          - pTagBackupSchedule
          - pTagOptOut
          - pTagDeploymentMethod
Parameters:
  pS3LifeCycleTransition:
    Type: String
    Description: Number of Days to retain the logs in Amazon S3 before transitioning the Logs to Amazon S3 Glacier.
  pLogArchiveAccountId:
    Type: String
    Description: "AWS Account Id where FlowLogs Bucket is deployed."
    AllowedPattern: '\d{12}'
  pSharedServicesAccountId:
    Description: AWS Account ID for Control Tower Shared Services Account
    Type: String
    AllowedPattern: '^[0-9]{12}$'
    ConstraintDescription: "This must be a 12 character string."
    MinLength: 12
    MaxLength: 12
  pAthenaQueryResultBucketArn:
    Type: String
    Description: The ARN of the Amazon S3 bucket to which Athena query results are stored. e.g. 'arn:aws:s3:::aws-athena-query-results-us-east-1-XXXXXXXXXXXXXX'
  pTagEnvironment:
    Type: String
    Description: Select the Name of the Environment
    AllowedValues:
      - Production
      - Non-Production
  pTagSDLC:
    Type: String
    Description: Distinguish between SDLC Environments e.g., Dev, Test, SIT, UAT
    AllowedValues:
      - Sandbox
      - Development
      - UAT
      - Staging
      - Production
      - Shared Services
  pTagApplicationName:
    Type: String
    Description: Identify resources that are related to a specific application
  pTagApplicationRole:
    Type: String
    Description: Identify the function of a particular respource e.g., Web Server, Message Broker, Database Server
  pTagCluster:
    Type: String
    Description: Identify resource farms that share a common configuration and perform a specific function for an application
  pTagDataClassification:
    Type: String
    Description: Identify the specific data confidentiality level a resource supports
    AllowedValues:
      - Public
      - Private
      - Confidential
      - Restricted
    Default: Private
  pTagCompliance:
    Type: String
    Description: Identify the specific compliance requirements that resources must adhere to e.g., PCI-DSS, HIPAA, ISO27001
  pTagDataRetention:
    Type: String
    Description: Identify the data retention policy applied to the resources (S3, ECR, CloudWatch Logs, EC2 AMI, EBS Snapshots, RDS Snapshot)
    AllowedValues:
      - 1
      - 3
      - 5
      - 7
      - 14
      - 30
      - 60
      - 90
      - 120
      - 150
      - 180
      - 365
      - 400
      - 545
      - 731
      - 1827
      - 3653
  pTagMapMigrated:
    Type: String
    Description: Identify resources that have been migrated as part of the AWS Migration Acceleration Program (MAP) for funding purposes
  pTagProjectName:
    Type: String
    Description: Identify projects that the resource supports
  pTagProductOwner:
    Type: String
    Description: Identify who is commercially responsible for the resource
  pTagTechnicalOwner:
    Type: String
    Description: Identify who is technically responsible for the resource
  pTagCostCenter:
    Type: String
    Description: Identify the cost center associated with a resource, typically for cost allocation and tracking
  pTagBusinessUnit:
    Type: String
    Description: Identify the business unit associated with a resource, typically for cost allocation and tracking
  pTagBusinessImpact:
    Type: String
    Description: Identify the business impact associated with the resource
    AllowedValues:
      - Critical
      - High
      - Medium
      - Low
    Default: Medium
  pTagEscalationPath:
    Type: String
    Description: Identify the next point of contact for a resource in an incident e.g, DevOps Team, 3rd Party Company
  pTagKnowledgeBase:
    Type: String
    Description: Identifies the location for knowledge base articles/wikis for the resource
  pTagHoursOfOperation:
    Type: String
    Description: Identify the hours of operation for a resource e.g., 24*7, 06:00 - 22:00 Monday - Friday, 08:00 - 18:00 Monday - Friday
    AllowedValues:
      - 24x7
      - 16x5
      - 9x5
    Default: 24x7
  pTagMaintenanceWindow:
    Type: String
    Description: Identify the hours in which a resource is available for maintenance to occur
  pTagBackupSchedule:
    Type: String
    Description: Identify the backup schedule for a resource
  pTagOptOut:
    Type: String
    Description: Identify whether a resource should be excluded from maintenance activities e.g., True, False
    AllowedValues:
      - "True"
      - "False"
    Default: "False"
  pTagDeploymentMethod:
    Type: String
    Description: Identify the method by which resources are deployed
    AllowedValues:
      - CloudFormation
      - Terraform
      - Manual
    Default: CloudFormation
Resources:
  rVpcFlowLogsSharedBucketStackSet:
    Type: AWS::CloudFormation::StackSet
    Properties:
      StackSetName: Centralised-Flowlogs-Shared-Bucket
      AdministrationRoleARN: !Sub arn:${AWS::Partition}:iam::${AWS::AccountId}:role/service-role/AWSControlTowerStackSetRole
      CallAs: SELF
      Capabilities:
        - CAPABILITY_NAMED_IAM
      Description: CloudFormation Template to Setup Destination S3 Bucket for Replicated VPC FlowLogs
      ExecutionRoleName: AWSControlTowerExecution
      ManagedExecution:
        Active: true
      OperationPreferences:
        FailureTolerancePercentage: 0
        MaxConcurrentPercentage: 100
        RegionConcurrencyType: PARALLEL
      PermissionModel: SELF_MANAGED
      StackInstancesGroup:
        - DeploymentTargets:
            Accounts:
              - !Ref pSharedServicesAccountId
          Regions:
            - !Ref AWS::Region
      TemplateURL: nested/centralised-flowlogs-shared-bucket.yaml
      Parameters:
        - ParameterKey: pS3LifeCycleTransition
          ParameterValue: !Ref pS3LifeCycleTransition
        - ParameterKey: pLogArchiveAccountId
          ParameterValue: !Ref pLogArchiveAccountId
        - ParameterKey: pAthenaQueryResultBucketArn
          ParameterValue: !Ref pAthenaQueryResultBucketArn
        - ParameterKey: pTagEnvironment
          ParameterValue: !Ref pTagEnvironment
        - ParameterKey: pTagSDLC
          ParameterValue: !Ref pTagSDLC
        - ParameterKey: pTagApplicationName
          ParameterValue: !Ref pTagApplicationName
        - ParameterKey: pTagApplicationRole
          ParameterValue: !Ref pTagApplicationRole
        - ParameterKey: pTagCluster
          ParameterValue: !Ref pTagCluster
        - ParameterKey: pTagCompliance
          ParameterValue: !Ref pTagCompliance
        - ParameterKey: pTagDataClassification
          ParameterValue: !Ref pTagDataClassification
        - ParameterKey: pTagDataRetention
          ParameterValue: !Ref pTagDataRetention
        - ParameterKey: pTagProjectName
          ParameterValue: !Ref pTagProjectName
        - ParameterKey: pTagProductOwner
          ParameterValue: !Ref pTagProductOwner
        - ParameterKey: pTagTechnicalOwner
          ParameterValue: !Ref pTagTechnicalOwner
        - ParameterKey: pTagCostCenter
          ParameterValue: !Ref pTagCostCenter
        - ParameterKey: pTagMapMigrated
          ParameterValue: !Ref pTagMapMigrated
        - ParameterKey: pTagBusinessUnit
          ParameterValue: !Ref pTagBusinessUnit
        - ParameterKey: pTagBusinessImpact
          ParameterValue: !Ref pTagBusinessImpact
        - ParameterKey: pTagEscalationPath
          ParameterValue: !Ref pTagEscalationPath
        - ParameterKey: pTagKnowledgeBase
          ParameterValue: !Ref pTagKnowledgeBase
        - ParameterKey: pTagHoursOfOperation
          ParameterValue: !Ref pTagHoursOfOperation
        - ParameterKey: pTagMaintenanceWindow
          ParameterValue: !Ref pTagMaintenanceWindow
        - ParameterKey: pTagBackupSchedule
          ParameterValue: !Ref pTagBackupSchedule
        - ParameterKey: pTagOptOut
          ParameterValue: !Ref pTagOptOut
        - ParameterKey: pTagDeploymentMethod
          ParameterValue: !Ref pTagDeploymentMethod
  rVpcFlowLogsBucketStackSet:
    DependsOn:
      - rVpcFlowLogsSharedBucketStackSet
    Type: AWS::CloudFormation::StackSet
    Properties:
      StackSetName: Centralised-Flowlogs-Bucket
      AdministrationRoleARN: !Sub arn:${AWS::Partition}:iam::${AWS::AccountId}:role/service-role/AWSControlTowerStackSetRole
      CallAs: SELF
      Capabilities:
        - CAPABILITY_NAMED_IAM
      Description: CloudFormation Template to Setup Source S3 Bucket for Replicated VPC FlowLogs
      ExecutionRoleName: AWSControlTowerExecution
      ManagedExecution:
        Active: true
      OperationPreferences:
        FailureTolerancePercentage: 0
        MaxConcurrentPercentage: 100
        RegionConcurrencyType: PARALLEL
      PermissionModel: SELF_MANAGED
      StackInstancesGroup:
        - DeploymentTargets:
            Accounts:
              - !Ref pLogArchiveAccountId
          Regions:
            - !Ref AWS::Region
      TemplateURL: nested/centralised-flowlogs-bucket.yaml
      Parameters:
        - ParameterKey: pS3LifeCycleTransition
          ParameterValue: !Ref pS3LifeCycleTransition
        - ParameterKey: pSharedServicesAccountId
          ParameterValue: !Ref pSharedServicesAccountId
        - ParameterKey: pTagEnvironment
          ParameterValue: !Ref pTagEnvironment
        - ParameterKey: pTagSDLC
          ParameterValue: !Ref pTagSDLC
        - ParameterKey: pTagApplicationName
          ParameterValue: !Ref pTagApplicationName
        - ParameterKey: pTagApplicationRole
          ParameterValue: !Ref pTagApplicationRole
        - ParameterKey: pTagCluster
          ParameterValue: !Ref pTagCluster
        - ParameterKey: pTagCompliance
          ParameterValue: !Ref pTagCompliance
        - ParameterKey: pTagDataClassification
          ParameterValue: !Ref pTagDataClassification
        - ParameterKey: pTagDataRetention
          ParameterValue: !Ref pTagDataRetention
        - ParameterKey: pTagProjectName
          ParameterValue: !Ref pTagProjectName
        - ParameterKey: pTagProductOwner
          ParameterValue: !Ref pTagProductOwner
        - ParameterKey: pTagTechnicalOwner
          ParameterValue: !Ref pTagTechnicalOwner
        - ParameterKey: pTagCostCenter
          ParameterValue: !Ref pTagCostCenter
        - ParameterKey: pTagMapMigrated
          ParameterValue: !Ref pTagMapMigrated
        - ParameterKey: pTagBusinessUnit
          ParameterValue: !Ref pTagBusinessUnit
        - ParameterKey: pTagBusinessImpact
          ParameterValue: !Ref pTagBusinessImpact
        - ParameterKey: pTagEscalationPath
          ParameterValue: !Ref pTagEscalationPath
        - ParameterKey: pTagKnowledgeBase
          ParameterValue: !Ref pTagKnowledgeBase
        - ParameterKey: pTagHoursOfOperation
          ParameterValue: !Ref pTagHoursOfOperation
        - ParameterKey: pTagMaintenanceWindow
          ParameterValue: !Ref pTagMaintenanceWindow
        - ParameterKey: pTagBackupSchedule
          ParameterValue: !Ref pTagBackupSchedule
        - ParameterKey: pTagOptOut
          ParameterValue: !Ref pTagOptOut
        - ParameterKey: pTagDeploymentMethod
          ParameterValue: !Ref pTagDeploymentMethod